version: 2

project_name: pp-substack

builds:
  - id: pp-substack
    main: ./cmd/pp-substack
    binary: pp-substack
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid= -X main.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: release
    ids:
      - pp-substack
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      mode: 0755
      mtime: 2000-01-01T00:00:00Z
    files:
      - src: LICENSE
        info:
          mode: 0644
          mtime: 2000-01-01T00:00:00Z
      - src: README.md
        info:
          mode: 0644
          mtime: 2000-01-01T00:00:00Z

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: github
